spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crestem-ong
    username: sa
    password: sa
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
    show-sql: true
  mail:
    host: localhost
    password: z0*!6zTcAUms
    port: 1025
    username: contact@crestemong.org
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 15728640
server:
  servlet:
    context-path: /api
logging:
  level:
    root: INFO
crestemong:
  security:
    allowed-origin-patterns: http://localhost:3000